.TH EPISODER 1 
.SH NAME
episoder \- TV show episode reminder.
.SH SYNOPSIS
.B episoder
[options]
.B COMMAND
.SH DESCRIPTION
episoder is a tool to tell you about new episodes of your favourite TV shows
.SH OPTIONS
.B \-h|\-\-help
Show help and quit.
.TP
.B \-c|\-\-rc \fIFILE\fR
Use \fIFILE\fR for configuration values (default is ~/.episoder).
.TP
.B \-n [days]
Specify the number of future days to be shown by showlist (default: 1)
.TP
.B \-v|--verbose
Enable verbose operation (builddb only)
.TP
.B \-w
Enable very verbose operation (builddb only)
.TP
.B \-V|\-\-version
Show program version and quit
.TP
.B -d [YYYY-MM-DD]
The date to begin search or update from (default: today)
.TP
.B    \-\-nodate
Ignore default cut-off date set in the config file (builddb) and ignore the date during search (showlist).
.TP
.B -s [string]
String to search all future episodes for
.TP
.B -i, --nocase
Case insensitive search (with -s or -sa)
.SH COMMANDS
.LP
.TP
.B builddb
Rebuild the database
.TP
.B showlist
Show the list of upcoming episodes
.SH PLUGINS
.LP
episoder uses a set of plugins to parse the source files. The plugins are called
episoder_plugin_pluginName.sh and are placed in the episoder home directory
(see below). Each plugin has to offer two functions:
.TP
.B match_pluginName
Returns something, if this plugin is supposed to be used for the URL (passed as $1).
Can be a simple grep for a known part of the URL, e.g. the domain name.
.TP
.B parse_pluginName
Parses $WGETFILE and generates a one-item-per-line list of the upcoming episodes.
The format is YYYY-MM-DD show episode.
.TP
In addition to that, the plugin has to add itself to the EPISODER_PLUGINS array. See episoder_plugin_tvcom.sh for an example.
.SH CONFIG FILE
.LP
The configuration file consists of a section with settings for the program
and a list of sources to be used to build the database.
.TP
.B agent=foo
Set the user-agent string to be used by wget (was required when tvtome blocked wget, might not be needed nowadays)
.TP
.B data=/path/to/file
Specifies the file to be used to store the information about upcoming shows.
.TP
.B src=http://some.web.add/ress
Each src entry specifies a URL with episode information. Make sure you have the
appropriate plugin before adding random new URLs (See \fBPLUGINS\fR).
.TP
.B format=unquoted format string
This allows you to customize episoder's output. Available fields are:
.PP
        %airdate     The episode's airdate as YYYY-MM-DD
        %show        Name of the show
        %season      Current season
        %epnum       Episode's number in season
        %eptitle     Title of the episode
        %totalep     Episode's total number
        %prodnum     Production number
.br

If undefined, the default value of 
.B %airdate %show %seasonx%epnum
(eg. "2005-07-29 Monk 4x04") is used.
.TP
.B dateformat=unquoted string describing the format
Here you can define the date format you'd like to be used for the output. To get a list of all possible fields, see
.BR date(1).

The default is %a, %b %d, %Y
.SH CRON
.LP
You might want to have your episode db rebuilt on a regular basis (i.e. daily).
The easiest way to achieve this is with a simple cron job:
.PP
    crontab -l > crontab
    echo "40 5 * * * episoder builddb" >> crontab
    crontab crontab
.br
.SH FILES
.B ~/.episoder
- default configuration file
.SH AUTHOR
This manual page was written by Stefan Ott
.SH "SEE ALSO"
.BR crontab(1).
