.TH EPISODER 1
.SH NAME
episoder \- TV show episode reminder.
.SH SYNOPSIS
.B episoder
[global options] [command] [command-specific options]
.SH COPYRIGHT
episoder is Copyright (C) 2004-2017 by Stefan Ott
.SH DESCRIPTION
episoder is a tool to tell you about new episodes of your favourite TV shows
.SH GLOBAL OPTIONS
.TP
.B \-h
Show help and quit.
.TP
.B \-c \fIFILE\fR
Use \fIFILE\fR for configuration values. By default ~/.episoder is used.
.TP
.B \-v, \-\-verbose
Enable verbose operation.
.TP
.B \-d, \-\-debug
Enable debug (very verbose) operation.
.TP
.B \-l \fIFILE\fR
Log to \fIFILE\fR instead of stdout.
.TP
.B \-V, \-\-version
Show program version and quit.
.SH COMMANDS
.SS Add Shows
.B episoder \fR[options] \fBadd\fR \fISHOW\fR
.PP
This adds a \fISHOW\fR to episoder's database. You can either specify a URL from epguides.com or a show ID from TheTVDB.com. Note that this won't fetch any episodes or meta data about the show, to do this you will need to \fBupdate\fR your database.
.SS Find Shows on TheTVDB.com
.B episoder \fR[options] \fBsearch \fI"search terms"\fR
.PP
Rather than visiting their web site you can use episoder to search TheTVDB.com.  This command will show you a list of all shows that match your \fIsearch terms\fR along with their IDs -- you will need to know these ids to \fBadd\fR shows to the database.
.SS List Shows
.B episoder \fR[options] \fBshows\fR
.PP
List all shows in episoder's database. The output contains information on the show's URL or TVDB ID, name, current state, the time of the last update and the number of episodes currently in the database.
.PP
The \fBshows\fR command knows the following extra options:
.TP
.B \-a, \-\-active
Only include shows that are currently running or suspended in the list.
.SS Remove Shows
.B episoder \fR[options] \fBremove \fISHOW\fR
.PP
This removes a \fISHOW\fR from episoder's database. Please specify the \fIshow id\fR as shown by the \fBshows\fR command.
.SS Disable Updates
.B episoder \fR[options] \fBdisable \fISHOW\fR
.PP
By default, any show that is added to episoder's database is included when the database is updated. If however you would like to disable updates for a certain show, this is how you do it.
.PP
Please specify the \fIshow id\fR as shown by the \fBshows \fRcommand.
.SS Enable Updates
.B episoder \fR[options] \fBenable \fISHOW\fR
.PP
Use this to re-enable updates for a show that has previously been \fIdisabled\fR. Please specify the \fIshow id\fR as shown by the \fBshows \fRcommand.
.SS Update the Database
.B episoder \fR[options] \fBupdate \fR[update-options]
.PP
Update the episoder database. This will fetch the list of known episodes for all shows that are currently in the database (unless they have been disabled).
.PP
The \fBupdate \fRcommand knows the following extra options:
.TP
.B \-d \fIDATE\fR
All episodes that are older than \fIDATE\fR will be removed from the database after the update. You can either specify an absolute date as \fIYYYY-MM-DD\fR or a relative date by passing the number of days back. The default value is 2, i.e.  all episodes more than two days old will be removed.
.TP
.B \-f, \-\-force
Update the database regardless of the time of the last update. By default episoder uses these update intervals:
.RS
.PP
* 2 days for shows that are currently running.
.PP
* 1 week for shows that are currently paused.
.PP
* 2 weeks for shows that have ended.
.RE
.TP
.B \-i, \-\-nodate
Don't remove any old episodes, regardless of their date.
.TP
.B \-s, \-\-show \fIID\fR
Only update the show with this \fIID\fR (as shown by the \fBshows \fRcommand), regardless of the last update time and whether or not updates are currently enabled for this show.
.TP
.B \-n, \-\-num \fINUM\fR
Limit the number of shows to be updated to \fINUM\fR. If you have a lot of shows in your database this option allows you to prevent load spikes, i.e. to distribute your updates more evenly by only updating a few of them at a time.
.TP
Note that the \fB-d\fP and \fB-i\fP options cannot be combined and that \fB-f\fP has no effect when using \fB-s\fP.
.SS List Episodes in the Database
.B episoder \fR[options] \fBlist \fR[list-options]
.PP
Show upcoming episodes. Before running this you should update the database to make sure that your list of episodes is up-to-date.
.PP
The \fBlist \fRcommand knows the following extra options:
.TP
.B \-C, \-\-nocolor
Don't use colors in the list of episodes. By default, episodes will be colored to indicate the air date relative to the current date:
.RS
.PP
* Episodes from the distant past are colored gray
.PP
* Yesterday's episodes are colored red
.PP
* Today's episodes are colored yellow
.PP
* Tomorrow's episodes are colored green
.PP
* Future episodes are colored cyan
.RE
.TP
.B \-d \fIDATE\fR
Only show episodes that air prior to \fIDATE\fR. You can either specify an absolute date as \fIYYYY-MM-DD\fR or a relative date by passing the number of days back. The default is to hide all episodes that aired before yesterday.
.TP
.B \-n \fIDAYS\fB, \-\-days \fIDAYS\fR
The number of days to show. Any episodes that are more than \fIDAYS\fR days in the future will be hidden. The default value is 2.

Note that this value is relative to the \fIDATE\fR specified with the \fB\-d \fRoption.
.TP
.B \-i, \-\-nodate
Show all episodes regardless of their date.
.TP
.B \-s \fISEARCH\fR
Search for \fISEARCH\fR in show and episode names.
.SS Send Notifications
.B episoder \fR[options] \fBnotify \fR[notify-options]
.PP
Send e-mail notifications about recently discovered episodes. You can run this command after \fBepisoder update \fRin order to get a friendly reminder about upcoming episodes to your INBOX.
.PP
The \fBnotify \fRcommand knows the following extra options:
.TP
.B \-d \fIDATE\fR
Only report episodes that air prior to \fIDATE\fR. You can either specify an absolute date as \fIYYYY-MM-DD\fR or a relative date by passing the number of days back. The default is TODO.
.TP
.B \-n \fIDAYS\fB, \-\-days \fIDAYS\fR
The number of days to include. Any episodes that are more than \fIDAYS\fR days in the future will be ignored. The default value is TODO (2?).
.TP
.B \-s \fIID\fB, \-\-show \fIID\fR
Only send notifications about episodes that belong to the show with the id \fIID\fR.
.TP
Note that you will need to configure your e-mail settings in the configuration file (see below for details).
.SH EXAMPLES
Find a show on TheTVDB.com:
.IP
.B episoder search dexter
.IP
The output will look like this:
.IP
.nf
ID      Name
------- --------------------
79349   Dexter
.fi

.TP
Add a show:
.IP
.B episoder add 79349

.TP
List all currently added shows:
.IP
.B
episoder shows
.IP
The output will look like this:
.IP
[   1] 79349
       Dexter, Running, Enabled
       Last update: 1970-01-01 00:00:00
       Episodes: 0

.TP
Fetch all episodes for Dexter regardless of the air date and enable debugging output:
.IP
.B episoder -d update -s 1 -i

.TP
List all episodes from October 2012:
.IP
.B episoder list -d 2012-10-01 -n 31
.SH CONFIG FILE
.LP
The configuration file contains default settings for episoder.
.TP
.B agent=foo
Set the user-agent string to be used when fetching data. This is only used for shows on epguides.com.
.TP
.B data=/path/to/file
Path to episoder's data file. If, instead of a file, you supply a database url (as expected by sqlalchemy, eg. 'mysql://localhost/episoder'), episoder is going to use that database for storage instead.
.TP
.B format=unquoted format string
This allows you to customize episoder's output. Available fields are:
.PP
        %airdate     The episode's airdate as YYYY-MM-DD
        %show        Name of the show
        %season      Current season
        %epnum       Episode's number in season
        %eptitle     Title of the episode
        %totalep     Episode's total number
        %prodnum     Production number
.br

If undefined, the default value of \fB%airdate %show %seasonx%epnum \fR(eg. "2005-07-29 Monk 4x04") is used.
.TP
.B dateformat=unquoted string describing the format
Here you can define the date format you'd like to be used for the output. To get a list of all possible fields, see
.BR date(1).

The default is %a, %b %d, %Y
.TP
.B tvdb_key=KEY
Use your own TVDB API \fIKEY\fR instead of episoder's built-in default key. This is recommended if you use episoder on a larger scale.

See http://thetvdb.com/?tab=apiregister for more details.
.TP
.B email_to=user@example.org
This is the e-mail address that will be used for notifications about new episodes. You will need to enter an address here to use the \fBnotify\fR feature.
.TP
.B email_server=localhost\fR, \fBemail_port=587
If you want to use an e-mail server other than localhost for sending notifications you can specify it here, along with the port number to connect to.
.TP
.B email_username=username\fR, \fBemail_password=password
If you need to authenticate against your mail server, this is where you can enter your user name and password.
.TP
.B email_tls=0
Set this to 1 to use TLS encryption to send your mail.
.SH CRON
.LP
You might want to have your episode database rebuilt on a regular basis (i.e. daily). The easiest way to achieve this is with a simple cron job:
.PP
    crontab \-l > crontab
    echo "40 5 * * * episoder update" >> crontab
    crontab crontab

.SH FILES
.B ~/.episoder
- default configuration file
.br
.B ~/.episodes
- default data file

.SH AUTHOR
This manual page was written by Stefan Ott
