.TH EPISODER 1 
.SH NAME
episoder \- TV show episode reminder.
.SH SYNOPSIS
.B episoder
[options]
.SH DESCRIPTION
episoder is a tool to tell you about new episodes of your favourite TV shows
.SH Global options
.TP
.B \-h
Show help and quit.
.TP
.B \-c \fIFILE\fR
Use \fIFILE\fR for configuration values (default is ~/.episoder).
.TP
.B \-b
Update episoder's database
.TP
.B \-v
Enable verbose operation
.TP
.B \-w
Enable very verbose (debug) operation
.TP
.B \-V
Show program version and quit
.TP
.B \-p
Show available parsers
.TP
.B \-l \fIFILE\fR
Log to \fIFILE\fR instead of stdout
.SH Options for database update
.TP
.B -d [YYYY-MM-DD]
Remove episodes prior to this date (default: yesterday)
.TP
.B -i
Ignore date (don't remove old episodes), overrules \-d
.TP
.B -f \fIFILE\fR
Get data from \fIFILE\fR, ignore configured sources (needs \-P)
.TP
.B -f \fIPARSER\fR
Force \fIPARSER\fR to be used (only in combination with \-f)
.SH Options for console output
.TP
.B -d [YYYY-MM-DD]
Only show episodes newer than date (default: yesterday)
.TP
.B -i
Ignore date (overrules \-d and \-n)
.TP
.B \-n \fIDAYS\fR
Number of future \fIDAYS\fR to show (default: 2). This value is relative to the date set with \-d.
.TP
.B -s \fITEXT\fR
Search the database for \fITEXT\fR
.TP
.B -C
Don't show any colors in the output
.SH CONFIG FILE
.LP
The configuration file consists of a section with settings for the program
and a list of sources to be used to build the database.
.TP
.B agent=foo
Set the user-agent string to be used by wget (was required when tvtome blocked wget, might not be needed nowadays)
.TP
.B data=/path/to/file
Specifies the file to be used to store the information about upcoming shows.
.TP
.B src=http://some.web.add/ress
Each src entry specifies a URL with episode information. Make sure you have the
appropriate plugin before adding random new URLs (check with \-p). Episoder currently understands the following types of source:
.PP
        src=http://www.epguides.com/CSI/
        src=http://www.tv.com/CSI/show/19/
.TP
.B src=http://some.web.add/ress name=some name
Optionally you can specify a name to use for your show instead of the one extracted from the website.
Be aware, however, that currently all spaces in the name you supply will be substituted by underscores.
.TP
.B format=unquoted format string
This allows you to customize episoder's output. Available fields are:
.PP
        %airdate     The episode's airdate as YYYY-MM-DD
        %show        Name of the show
        %season      Current season
        %epnum       Episode's number in season
        %eptitle     Title of the episode
        %totalep     Episode's total number
        %prodnum     Production number
.br

If undefined, the default value of
.B %airdate %show %seasonx%epnum
(eg. "2005-07-29 Monk 4x04") is used.
.br

Whether this option is honored or not is up to the chosen output plugin.
.TP
.B dateformat=unquoted string describing the format
Here you can define the date format you'd like to be used for the output. To get a list of all possible fields, see
.BR date(1).

The default is %a, %b %d, %Y
.SH CRON
.LP
You might want to have your episode db rebuilt on a regular basis (i.e. daily).
The easiest way to achieve this is with a simple cron job:
.PP
    crontab \-l > crontab
    echo "40 5 * * * episoder \-b" >> crontab
    crontab crontab
.br
.SH FILES
.B ~/.episoder
- default configuration file
.SH AUTHOR
This manual page was written by Stefan Ott
.SH "SEE ALSO"
.BR crontab(1).
