#!/bin/bash
# episoder, http://episoder.sourceforge.net/
#
# Copyright (c) 2004, 2005 Stefan Ott. All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
# $Id$

EPISODER_VERSION=0.4.0
EPISODER_HOME=/usr/share/episoder

show_help() {
	echo Usage: $0 [options] 
	echo 
	echo Valid options:
	echo "	-h, --help	show this help"
	echo "	-c, --rc=FILE	use configuration from FILE (default: ~/.episoder)"
	echo "	-b		build the database"
	echo "	-v, --verbose	verbose operation (-b only)"
	echo "	-w		very verbose operation (-b only)"
	echo "	-V, --version	get version information"
	echo "	-n [days]	number of future days to show (default: 1)"
	echo "	-d [YYYY-MM-DD]	date to begin search or update from"
	echo "	-i  --nodate	ignore date"
	echo "	-s [string]	string to search for"
}

set_verbose() {
	export VERBOSE=true
}

set_very_verbose() {
	set_verbose
	export VERY_VERBOSE=true
	export WGET_ARGS="-v -t 5 --retry-connrefused "
}

set_nodate() {
	export NODATE=true
}

show_version() {
	echo episoder v$EPISODER_VERSION
}

set_builddb() {
	COMMAND=builddb
}

episoder_dump() {
	echo "Config file = ${EPISODER_RC_FILE}"
	echo "Command = ${COMMAND}"
	echo "Days = ${NUM_DAYS}"
	echo "Episoder version = ${EPISODER_VERSION}"
	echo "Ignore date = ${NODATE}"
	echo "Search text = ${SEARCH_TEXT}"
	echo "Startdate = ${DATE_TEXT}"
	echo "Wget arguments = ${WGET_ARGS}"
	echo "Verbose = ${VERBOSE}"
	echo "Very verbose = ${VERY_VERBOSE}"
}

	# set some default values
	EPISODER_RC_FILE=${HOME}/.episoder
	NUM_DAYS=1
	SEARCH_TEXT=""
	DATE_TEXT=""
	COMMAND="showlist"

	while getopts  "c:d:hin:s:vVwb" flag ; do
		case "$flag" in
			h)
				show_help ; exit 0 ;;
			c)
				EPISODER_RC_FILE=$OPTARG ;;
			v)
				set_verbose ;;
			w)
				set_very_verbose ;;
			V)
				show_version ; exit 0 ;;
			n)
				NUM_DAYS=$OPTARG ;;
			d)
				DATE_TEXT=$OPTARG ;;
			i)
				set_nodate ;;
			s)
				SEARCH_TEXT=$OPTARG ;;
			b)
				set_builddb ;;
			*)
				show_help ; exit 1 ;;
		esac
	done

	shift $((OPTIND-1))

	if [ ! -z "$1" ]; then
		COMMAND=$1
	fi

	if [ -z "$COMMAND" ]; then show_help; exit 1; fi

	if [ ! -f "$EPISODER_RC_FILE" ]; then
		echo "$0: Configuration file $EPISODER_RC_FILE does not exist / is not a regular file"
		exit 1
	fi

	EPISODER_DATAFILE=`cat $EPISODER_RC_FILE | grep '^data=' | cut -b 6-`
	WGET_USER_AGENT=`cat $EPISODER_RC_FILE | grep '^agent=' | cut -b 7-`
	OUTPUT_FORMAT=`cat $EPISODER_RC_FILE | grep '^format=' | cut -b 8-`
	DATE_FORMAT=`cat $EPISODER_RC_FILE | grep '^dateformat=' | cut -b 12-`
	DEFAULT_DATE=`cat $EPISODER_RC_FILE | grep '^default_date=' | cut -b 14-`

	if [ -z "$EPISODER_DATAFILE" ]; then
		echo "$0: No data file specified in configuration file"
		exit 1
	fi
	if [ -z "$OUTPUT_FORMAT" ]; then
		OUTPUT_FORMAT="%airdate %show %seasonx%epnum"
	fi
	if [ $COMMAND = "builddb" ]; then
		if [ -z "$DEFAULT_DATE" ]; then
			if [ -z $DATE_TEXT ]; then
				TODAY=`date +%Y-%m-%d`
				DATE_TEXT=$TODAY
			fi
		else
			if [ -z "$NODATE" ]; then
				DATE_TEXT=$DEFAULT_DATE
			fi
		fi
	fi



case "$COMMAND" in
	builddb)
	    . $EPISODER_HOME/episoder-builddb.sh
		build_db
		;;
	showlist)
		. $EPISODER_HOME/episoder-showlist.sh
		show_episode_list
		;;
	dump)
		episoder_dump
		;;
	*)
		show_help
		exit 1
esac
